// examples/grig-demo-react/src/App.tsx
import Content from "./components/Content";

import "./App.css";

import SwitchLang from "./components/SwitchLang";
import { GrigProvider } from "./lang/init";


function App() {
    return (
        <GrigProvider>
            <div className="app card">
                <div>app.tsx</div>
                <SwitchLang />
                <Content />
            </div>
        </GrigProvider>
    );
}

export default App;

// examples/grig-demo-svetle/src/App.svelte
<script lang="ts">
  import Content from "./components/Content.svelte";
  import SwitchLang from "./components/SwitchLang.svelte";
  import { tMessages } from "./lang/init";
  const t = tMessages();
</script>

<div class="app card">
  <div>app.svelte</div>
  <SwitchLang />
  <Content />
</div>

<style>
</style>
