// examples/grig-demo-svetle-key-refresh/src/components/SwitchLang.svelte
<script lang="ts">
    import { tMessages, setLang, getLang } from "../lang/init";

    const t = tMessages({
        zh: { lang: "中文", }, en: { lang: "English", },
    });
  </script>
  
  <div class="lang-switch card">
    <div>child: SwitchLang.svelte</div>
    <button
        on:click={() => {
            setLang(getLang() === "en" ? "zh" : "en");
        }}
    >
        {getLang()} {t("lang")}
    </button>
</div>

// examples/grig-demo-nextjs/src/components/SwitchLang.tsx
import { tMessages, useGrigContext } from "../lang/init";

const SwitchLang = () => {
    const { lang, setLang } = useGrigContext();
    const t = tMessages({
        zh: {
            lang: "中文",
        },
        en: {
            lang: "English",
        },
    });
    return (
        <div className="lang-switch card">
            <div>child: SwitchLang.tsx</div>
            <button
                onClick={() => {
                    setLang(lang === "en" ? "zh" : "en");
                }}
            >
                {lang} {t("lang")}
            </button>
        </div>
    );
};
export default SwitchLang;
