// examples/grig-demo-svetle-key-refresh/src/App.svelte
<script lang="ts">
  import Counter from "./lib/Counter.svelte";
  import Content from "./components/Content.svelte";
  import SwitchLang from "./components/SwitchLang.svelte";
  import {
    getLang,
    addLangChangeCallback,
    removeLangChangeCallback,
  } from "./lang/init";
  import { onDestroy, onMount } from "svelte";
  let lang: string = getLang();
  onMount(() => {
    addLangChangeCallback("langChange", (_lang: string) => {
      lang = _lang;
    });
  });
  onDestroy(() => {
    removeLangChangeCallback("langChange");
  });
</script>

<div class="app card">
  {#key lang}
  <div>app.sevelte</div>
  <SwitchLang />
    <Content />
 
  {/key}
</div>

<style>
</style>

// examples/grig-demo-prect-key-fresh/src/app.tsx
import "./app.css";
import SwitchLang from "./components/SwitchLang";
import Content from "./components/Content";
import { useEffect, useState } from "react";
import {
    addLangChangeCallback,
    getLang,
    removeLangChangeCallback,
} from "./lang/init";

export function App() {
    const [lang, setLang] = useState(getLang());
    useEffect(() => {
        addLangChangeCallback("langChange", (_lang) => {
            setLang(_lang);
        });
        return () => {
            removeLangChangeCallback("langChange");
        };
    }, []);

    return (
        <>
            <div className="app card" key={lang}>
                <div>app.tsx</div>
                <SwitchLang />
                <Content />
            </div>
        </>
    );
}
